### ISSUE TITLE
MULTIPLE_MAILING_LISTS_IN_CAMPAIGNS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by alexrett** [moosend/phpwrapper#1]
when i call `$moosendApi->campaigns->getCampaigns(1, 10, 'CreatedOn', 'DESC');`
return subject

and also in default params getCampaigns 
`public function getCampaigns(/* int */ $page = 1, /* int */ $pageSize = 10, /* string */ $sortBy = 'ASC', /* string */ $sortMethod = 'CreatedOn') {`

value of the parameters are messed up places

**Comment by jtourkos** [comment]
Multiple mailing lists are not currently supported. If you are receiving an error this is probably caused by a campaign sent in multiple mailing lists. This API call does not support that. So removing that campaign should not give you an error. Multiple mailing lists will be supported as soon as Moosend API v3 is released.

The default parameters are indeed in false order. It should be `public function getCampaigns(/* int */ $page = 1, /* int */ $pageSize = 10, /* string */ $sortBy = 'CreatedOn', /* string */ $sortMethod = 'ASC') {...}` Will fix it right away.  
Thanks!
